ALTER TABLE orders
    MODIFY COLUMN status ENUM(
        'PENDING', 'PENDING_PAYMENT', 'CONFIRMED', 'PROCESSING',
        'SHIPPED', 'DELIVERED', 'CANCELLED', 'EXPIRED', 'REFUNDED'
    ) NOT NULL DEFAULT 'PENDING',
    MODIFY COLUMN payment_method ENUM(
        'COD', 'CREDIT_CARD', 'BANK_TRANSFER', 'E_WALLET', 'VIETQR'
    ) NOT NULL;

ALTER TABLE order_status_history
    MODIFY COLUMN from_status ENUM(
        'PENDING', 'PENDING_PAYMENT', 'CONFIRMED', 'PROCESSING',
        'SHIPPED', 'DELIVERED', 'CANCELLED', 'EXPIRED', 'REFUNDED'
    ),
    MODIFY COLUMN to_status ENUM(
        'PENDING', 'PENDING_PAYMENT', 'CONFIRMED', 'PROCESSING',
        'SHIPPED', 'DELIVERED', 'CANCELLED', 'EXPIRED', 'REFUNDED'
    ) NOT NULL;
